In [ ]:
# NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
num = [58,89,25,20]
arr1=np.array(num)

In [3]:
arr1

array([58, 89, 25, 20])

In [5]:
arr1.ndim

1

In [6]:
arr1.shape

(4,)

In [7]:
arr2=np.array([[48,50,25,63],[89,58,25,41]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr2

array([[48, 50, 25, 63],
       [89, 58, 25, 41]])

In [11]:
np.linspace(10,30)

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [12]:
np.linspace(10,30,10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
arr3=np.arange(1,101)

In [17]:
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [18]:
arr4=np.arange(1,101,5)

In [19]:
arr4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [20]:
np.random.randint(10,45,50)

array([38, 30, 43, 13, 35, 13, 13, 40, 25, 31, 23, 32, 14, 10, 26, 23, 30,
       18, 41, 17, 26, 35, 20, 32, 16, 13, 24, 33, 43, 29, 37, 23, 17, 16,
       34, 29, 14, 26, 21, 10, 18, 12, 42, 33, 11, 10, 16, 42, 27, 43])

In [21]:
np.random.seed(1)
arr5=np.random.randint(10,45,100)

In [ ]:
###### 

In [22]:
arr5

array([22, 18, 19, 21, 15, 25, 10, 26, 11, 22, 17, 16, 35, 30, 28, 30, 21,
       38, 39, 24, 14, 33, 33, 40, 42, 32, 23, 19, 17, 32, 11, 10, 27, 18,
       34, 23, 18, 40, 17, 13, 16, 31, 13, 14, 34, 22, 36, 26, 28, 25, 10,
       14, 35, 44, 33, 17, 36, 35, 32, 19, 13, 33, 37, 29, 18, 42, 44, 20,
       33, 25, 33, 35, 17, 38, 20, 42, 34, 33, 11, 23, 13, 10, 23, 16, 31,
       16, 12, 22, 37, 31, 21, 17, 23, 18, 21, 22, 30, 40, 17, 14])

In [23]:
arr6=arr5.reshape(10,10)

In [24]:
arr6

array([[22, 18, 19, 21, 15, 25, 10, 26, 11, 22],
       [17, 16, 35, 30, 28, 30, 21, 38, 39, 24],
       [14, 33, 33, 40, 42, 32, 23, 19, 17, 32],
       [11, 10, 27, 18, 34, 23, 18, 40, 17, 13],
       [16, 31, 13, 14, 34, 22, 36, 26, 28, 25],
       [10, 14, 35, 44, 33, 17, 36, 35, 32, 19],
       [13, 33, 37, 29, 18, 42, 44, 20, 33, 25],
       [33, 35, 17, 38, 20, 42, 34, 33, 11, 23],
       [13, 10, 23, 16, 31, 16, 12, 22, 37, 31],
       [21, 17, 23, 18, 21, 22, 30, 40, 17, 14]])

In [25]:
arr6[4,5]

22

In [26]:
arr6[2:7,3:7]

array([[40, 42, 32, 23],
       [18, 34, 23, 18],
       [14, 34, 22, 36],
       [44, 33, 17, 36],
       [29, 18, 42, 44]])

In [27]:
arr6[2:7,3:7]=25

In [28]:
arr6

array([[22, 18, 19, 21, 15, 25, 10, 26, 11, 22],
       [17, 16, 35, 30, 28, 30, 21, 38, 39, 24],
       [14, 33, 33, 25, 25, 25, 25, 19, 17, 32],
       [11, 10, 27, 25, 25, 25, 25, 40, 17, 13],
       [16, 31, 13, 25, 25, 25, 25, 26, 28, 25],
       [10, 14, 35, 25, 25, 25, 25, 35, 32, 19],
       [13, 33, 37, 25, 25, 25, 25, 20, 33, 25],
       [33, 35, 17, 38, 20, 42, 34, 33, 11, 23],
       [13, 10, 23, 16, 31, 16, 12, 22, 37, 31],
       [21, 17, 23, 18, 21, 22, 30, 40, 17, 14]])

In [29]:
arr6>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [30]:
arr6[arr6>35]

array([38, 39, 40, 37, 38, 42, 37, 40])

In [31]:
arr6[arr6==35]

array([35, 35, 35, 35])

In [32]:
np.max(arr6)

42

In [34]:
np.min(arr6)

10

In [35]:
np.mean(arr6)

23.98

In [36]:
np.median(arr6)

25.0

In [39]:
np.std(arr6)

7.999974999960938

In [40]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes